/**
 * Component registry generator for Vite apps.
 * Adapted from packages/next-plugin/src/preview-route.ts.
 * Writes a static import map into the target app's src directory.
 */

import fs from "fs";
import path from "path";

const REGISTRY_FILE = "designtools-registry.ts";

/** Generate the component registry file in the target app's src directory. */
export function generateComponentRegistry(
  projectRoot: string,
  componentDir?: string
): void {
  const srcDir = path.join(projectRoot, "src");
  const componentPaths = discoverComponentFiles(projectRoot, componentDir);

  const registryEntries = componentPaths
    .map((p) => {
      // Strip leading src/ for @/ alias (since @ maps to src/)
      const importPath = p.startsWith("src/") ? p.slice(4) : p;
      return `  "${p}": () => import("@/${importPath}"),`;
    })
    .join("\n");

  const content = `// Auto-generated by @designtools/vite-plugin — do not edit

const COMPONENT_REGISTRY: Record<string, () => Promise<any>> = {
${registryEntries}
};

if (typeof window !== "undefined") {
  (window as any).__DESIGNTOOLS_REGISTRY__ = COMPONENT_REGISTRY;
}

export function DesigntoolsRegistry() {
  return null;
}
`;

  fs.writeFileSync(path.join(srcDir, REGISTRY_FILE), content, "utf-8");
  ensureGitignore(projectRoot);
}

/** Clean up generated registry file. */
export function cleanupComponentRegistry(projectRoot: string): void {
  const registryPath = path.join(projectRoot, "src", REGISTRY_FILE);
  try {
    fs.unlinkSync(registryPath);
  } catch {
    // ignore
  }
}

function ensureGitignore(projectRoot: string): void {
  const gitignorePath = path.join(projectRoot, ".gitignore");
  const entry = "src/designtools-registry.ts";

  try {
    const existing = fs.existsSync(gitignorePath)
      ? fs.readFileSync(gitignorePath, "utf-8")
      : "";
    if (!existing.includes(entry)) {
      fs.appendFileSync(
        gitignorePath,
        `\n# Generated by @designtools/vite-plugin\n${entry}\n`
      );
    }
  } catch {
    // ignore if we can't write gitignore
  }
}

function discoverComponentFiles(
  projectRoot: string,
  overrideDir?: string
): string[] {
  const dirs = overrideDir
    ? [overrideDir]
    : ["src/components/ui", "components/ui"];
  for (const dir of dirs) {
    const fullDir = path.join(projectRoot, dir);
    if (fs.existsSync(fullDir)) {
      const files = fs.readdirSync(fullDir);
      return files
        .filter(
          (f) => f.endsWith(".tsx") || f.endsWith(".ts") || f.endsWith(".jsx")
        )
        .map((f) => `${dir}/${f.replace(/\.(tsx|ts|jsx|js)$/, "")}`);
    }
  }
  return [];
}
